<MyLayout>
    BoxLayout:
        orientation: "vertical" #horizontal,vertical
        size:root.width,root.height
        spacing:20
        #padding_top:20
        padding:50
        Button:
            text: "hello"
        Button:
            text: "I am"
        Button:
            text: "akhilesh"
            pos_hint: {'center_x':.5}
            size_hint:(None,None) #(1,.3)
            width:200 
            height:50