
<MyLayout>
    BoxLayout:
        orientation:"vertical"
        size:root.width,root.height
        padding:20
        spacing:20
        Carousel:
        # use "top","bottom","left","right"
            direction:"right"
            Image:
                source:"image/image2.jpg"
            Image:
                source:"image/image1.jpg"
            Image:
                source:"image/image.jpg"
            

