
<MyLayout>
    do_default_tab:False
    tab_pos:"top_mid"
    TabbedPanelItem:
        text:"tab 1"
        Label:
            text :"hellow"
    TabbedPanelItem:
        text:"tab 2"
        BoxLayout:
            
            Label:
               
                text :"click me !!"
            Button:
                text:"click"
    TabbedPanelItem:
        text:"tab 3"
        Image:
            source:"image/image13.jpg"
            

