<MyLayout>
    BoxLayout:
        orientation:"vertical"
        size:root.width,root.height
        Label:
            id:text
            text:"what is your name?"
            font_size:32
        TextInput:
            id:name
            multiline:False
            size_hint:(1,.5)
        Button:
            text:"Submit"
            font_size:32
            size_hint:(1,.5)
            on_press:root.press()
            
        